<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DepartmentSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('departments')->insert([
            [
                'category_id' => 1,
                'company_id' => 1,
                'department_name' => 'Operations',
                'department_code' => 'OPS',
                'department_head' => 'Operations Head',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 2,
                'company_id' => 1,
                'department_name' => 'Credit & Quality',
                'department_code' => 'CRQ',
                'department_head' => 'Quality Manager',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 3,
                'company_id' => 1,
                'department_name' => 'Company Secretary & Compliance',
                'department_code' => 'CSC',
                'department_head' => 'Compliance Officer',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 5,
                'company_id' => 1,
                'department_name' => 'HR & Admin',
                'department_code' => 'HRAD',
                'department_head' => 'HR Manager',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 5,
                'company_id' => 1,
                'department_name' => 'Finance & Accounts',
                'department_code' => 'FIN',
                'department_head' => 'Finance Manager',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 6,
                'company_id' => 1,
                'department_name' => 'MIS & IT',
                'department_code' => 'MISIT',
                'department_head' => 'IT Manager',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 3,
                'company_id' => 1,
                'department_name' => 'Strategy & Corporate Communication',
                'department_code' => 'STRCOM',
                'department_head' => 'Strategy Head',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 7,
                'company_id' => 1,
                'department_name' => 'Training',
                'department_code' => 'TRN',
                'department_head' => 'Training Manager',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 2,
                'company_id' => 1,
                'department_name' => 'Risk Control & Audit',
                'department_code' => 'RCA',
                'department_head' => 'Audit Head',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 5,
                'company_id' => 1,
                'department_name' => 'Co-ordination, Grievances & Customer Relationship',
                'department_code' => 'CGCR',
                'department_head' => 'CRM Head',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 5,
                'company_id' => 1,
                'department_name' => 'Admin',
                'department_code' => 'ADM',
                'department_head' => 'Admin Manager',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 2,
                'company_id' => 1,
                'department_name' => 'Concurrent Audit',
                'department_code' => 'CAUD',
                'department_head' => 'Audit Manager',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 6,
                'company_id' => 1,
                'department_name' => 'CEO',
                'department_code' => 'CEO',
                'department_head' => 'Chief Executive Officer',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 5,
                'company_id' => 1,
                'department_name' => 'Business Loan',
                'department_code' => 'BLN',
                'department_head' => 'Loan Manager',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
        ]);
    }
}
